alias ga="git add"
alias gco="git checkout"
alias gcm="git commit"
alias glg="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gsh="git show"
alias gs="git status"
alias grm="git rm"
alias grb="git rebase -i"
alias gbr="git branch"
alias gbrs="git branch -a"
alias gdt="git difftool -y"
alias gtg="git tag"
alias gtgs="git tag -l"
alias gres="remote -v"
