#!/bin/sh
#
#  Control the backup of mysql
#
#  https://github.com/michaelbragg/dotfiles/blob/master/osx/mysql/mysqldb
#
#  Michael Bragg  |  @michaelbragg  |  http://michaelbragg.net

function help () {
  echo "mysql - A simple script that allows you to mange your MySQL database from the comandline."
  echo ""
  echo "    mysqldb backup                  - backs up whole MySQL database";
  echo ""
}

# Set the location for the database dump
outputdir=~/Downloads

function backup () {
  now="`date +'%Y-%m-%d_%H-%M-%S'`"
  location=${outputdir}/localhost_${now}.sql
  mysqldump --all-databases > ${location}
  echo "Database backed up to ${location}";
}

function backupTable () {
  now="`date +'%Y-%m-%d_%H-%M-%S'`"
  location=${outputdir}/$1_${now}.sql
  mysqldump --single-transaction $1 > ${location}
  echo "Database backed up to ${location}";
}

case "$1" in
  backup)
    if [ $2 ]
      then
        backupTable "$2"
      else
        backup
    fi
  ;;
  *)
    help
  ;;
esac
