#!/bin/sh
#
# Auto install software on OSX
#
# Run osx/setup and you'll be good to go.

# Test for Command Line Tools for Xcode

# homebrew

if test ! $(which brew)
then
  echo "Installing Homebrew"
  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  exit
fi

# Install homebrew packages

brew install grc coreutils spark

# Check to see if git is installed by homebrew
if [ $(which  git) != "/usr/local/bin/git" ]
then
 echo "Installing GIT"
 brew install git
fi

exit 0